fbrew, speed up more actions and fix error.

diff --git a/.local/zbin/fbrew b/.local/zbin/fbrew
--- a/.local/zbin/fbrew
+++ b/.local/zbin/fbrew
@@ -56,11 +56,18 @@ elif [[ $src == --cask ]]; then
   descs=`brew --cache`/cask_descriptions.json
 fi
 
+local fzf_list
+if (( $cmds_installed[(I)$opts[1]] )); then
+  fzf_list=`brew --cache`/fzf$src-list-installed-`machine`.txt
+else
+  fzf_list=`brew --cache`/fzf$src-list-complete-`machine`.txt
+fi
+
 # - delete *descriptions.json. It's not refreshed with new formulae/casks.
 # - delete fzf_list to rebuild listing.
 # - save new formulae/casks names to present later in fzf.
 if [[ -f $names.last.txt && -f $names.txt ]]; then
-  local new_keys new_hold fzf_list=`brew --cache`/fzf$src-list-`machine`.txt
+  local new_keys new_hold
 
   new_keys=( `comm -1 -3 $names.last.txt $names.txt` )
   new_hold=$names.new-`print -- ${new_keys[@]} | md5`.txt
@@ -77,17 +84,17 @@ if [[ ! -f $names.txt ]]; then
 fi
 cp -f $names.txt $names.last.txt
 
-local lsdesc
-if (( $cmds_any[(I)$opts[1]] )); then
-  local state
-  if [[ $src == --formula ]]; then
-    state=`/bin/ls $( brew --cellar ) | md5`
-  elif [[ $src == --cask ]]; then
-    state=`/bin/ls $( brew --caskroom ) | md5`
-  fi
+local lsdesc state
+if [[ $src == --formula ]]; then
+  state=`/bin/ls $( brew --cellar ) | md5`
+elif [[ $src == --cask ]]; then
+  state=`/bin/ls $( brew --caskroom ) | md5`
+fi
 
-  if [[ ! -f $fzf_list ]] \
-  || [[ -f $fzf_list && $state != `sed '1!d' $fzf_list` ]]; then
+if [[ ! -f $fzf_list ]] \
+|| [[ -f $fzf_list && $state != `sed '1!d' $fzf_list` ]]; then
+  if (( $cmds_any[(I)$opts[1]] )); then
+
     typeset -a reqs deps
     if [[ $src == --formula ]]; then
       reqs=( `brew ls --installed-on-request` )
@@ -101,6 +108,8 @@ if (( $cmds_any[(I)$opts[1]] )); then
     for f in $names.new-*.txt(N); new+=( `cat $f` )
 
     # this works around regex capture limits in sed. limit each loop to 100 names.
+    # it can still fail if many names are very long, e.g., font migration to casks.
+    # it would be smarter to limit based on bytes.
     local limit=100
     local maxcount=0 a=1 z=$limit
     for n in ${#reqs} ${#deps} ${#new}; do
@@ -108,7 +117,6 @@ if (( $cmds_any[(I)$opts[1]] )); then
     done
 
     lsdesc=`brew desc $src --eval-all --search ".+"`
-
     repeat `bc -le "ceil($(( $maxcount / $limit.0 )),0)"`; do
       lsdesc=`print -- $lsdesc | \
         sed -uE "s/^(${(j[|])deps[$a,$z]}):(.*)/\1:🌾 dependency.\2/" | \
@@ -116,20 +124,27 @@ if (( $cmds_any[(I)$opts[1]] )); then
         sed -uE "s/^(${(j[|])new[$a,$z]}):(.*)/\1:⏰ new.\2/"`
       a=$(( $a + $limit )) z=$(( $z + $limit ))
     done
-
     printf "%s\n%s\n" $state $lsdesc > $fzf_list
-  else
-    lsdesc=`cat $fzf_list | sed 1,1d`
-  fi
 
-elif (( $cmds_installed[(I)$opts[1]] )); then
-  local filter
-  if [[ $src == --formula ]]; then
-    filter=( `brew ls --installed-on-request` )
-  elif [[ $src == --cask ]]; then
-    filter=( `brew ls --cask` )
+  elif (( $cmds_installed[(I)$opts[1]] )); then
+
+    local filter
+    if [[ $src == --formula ]]; then
+      filter=( `brew ls --installed-on-request` )
+    elif [[ $src == --cask ]]; then
+      filter=( `brew ls --cask` )
+    fi
+
+    if [[ ${#filter} > 0 ]]; then
+      lsdesc=`brew desc $src ${filter[@]}`
+      printf "%s\n%s\n" $state $lsdesc > $fzf_list
+    else
+      print "Nothing to list for '${opts[@]}'." >&2
+      return 1
+    fi
   fi
-  lsdesc=`brew desc $src ${filter[@]}`
+else
+  lsdesc=`cat $fzf_list | sed 1,1d`
 fi
 
 local sids
