Clean up and bug fixes for bdefaults script.

diff --git a/.config/backup/bdefaults b/.config/backup/bdefaults
--- a/.config/backup/bdefaults
+++ b/.config/backup/bdefaults
@@ -57,8 +57,7 @@ function sbackup() {
       echo "  $1 > $2 - saved"
 
     # Ensure the index is unique.
-    index=(${(f)"$(sgetIndex $1)"})
-    if [[ ${2:|index} ]]; then
+    if ! sgetIndex $1 | grep -qxF $2; then
       plutil -insert SettingsIndex -string $2 -append $plist
     fi
   else
@@ -75,7 +74,7 @@ function srestore() {
     defaults write $1 $2 "$value" &&
       echo "  $1 < $2 - restored"
   else
-    echo "!!$1 ! $2 - failed!"
+    echo "!!$1 ! $2 - failed!" >&2
   fi
 }
 
@@ -93,11 +92,8 @@ function slistDomain() {
 
 # $1 domain
 # $2 key
-# returns 0 when it exists, 1 when it doesn't.
 function skeyExists() {
-  typeset -A r=(0 1 1 0)
-  local i=(${(f)"$(sgetIndex $1)"})
-  return $r[$i[(Ie)$2]]
+  sgetIndex $1 | grep -qxF $2
 }
 
 # $1 domain
@@ -131,88 +127,89 @@ function () {
     op=$1; shift 1
   fi
 
-  if [[ -n $help ]]; then
-    shelp
-  elif [[ $op != (backup|restore|list) ]]; then
-    errmsg="backup, restore or list action required."
-  elif [[ ${#key[@]} > 2 || ${#domain[@]} > 2 ]]; then
-    errmsg="Conflicting arguments:`printf " %s" $key $domain`"
-  elif [[ ${#@[@]} > 0 ]]; then
-    errmsg="Unknown arguments: $@"
-  fi
+  [[ -n $help ]] && shelp
+
+  [[ $op != (backup|restore|list) ]] && errmsg+=(
+    "backup, restore or list action is required."
+  )
+  [[ -n $search && $op == restore ]] && errmsg+=(
+    "Cannot $op with search! Omit the $search flag."
+  )
+  [[ -n $search && $key == (-e|--existing) ]] && errmsg+=(
+    "Cannot use $key with search! Use -k <setting> instead."
+  )
+  [[ -z $key ]] && errmsg+=(
+    "-k or -e is required."
+  )
+  [[ ${#key[@]} > 2 ]] && errmsg+=(
+    "Conflicting keys: $key"
+  )
+  [[ ${#domain[@]} > 2 ]] && errmsg+=(
+    "Conflicting domains: $domain"
+  )
+  [[ ${#@[@]} > 0 ]] && errmsg+=(
+    "Unknown arguments: $@"
+  )
 
   bdpath=${_path[-1]:-$bdpath}
   if [[ ! -d $bdpath ]]; then
     case $op in
-      backup)       mkdir -p $bdpath                           ;;
-      restore|list) errmsg="No backups found in path: $_path" ;;
+      backup)       mkdir -p $bdpath                            ;;
+      restore|list) errmsg+=("No backups found in path: $_path");;
     esac
   fi
 
   if [[ -n $errmsg ]]; then
-    echo $errmsg >&2; shelp 1
+    printf " %s\n" $errmsg >&2
+    shelp 1
   fi
 
   if [[ -n $search ]]; then
-    if [[ $op != (backup|list) ]]; then
-      echo "Cannot $op with $search ! Omit the $search flag." >&2
-      shelp 1
-    elif [[ $key == (-e|--existing) ]]; then
-      echo "Conflicting arguments! Cannot search active domains with $key !" >&2
-      echo "Use $search with -k <setting> to $op beyond existing backed up keys!" >&2
-      shelp 1
-    elif [[ -z $key ]]; then
-      echo "Missing key." >&2
-      shelp 1
-    else
 
-      # [backup|list] by searching across all active domains for a given key.
-      echo "Searching active domains for $key…"
-      op=${op/list/listDomain}
-      while read -r l; do
-        if [[ $l =~ "Found [0-9]+ keys in domain '([^']*)'" ]]; then
-          # If there's a match, skip to next item in the loop.
-        elif [[ -n $match[1] ]]; then
-          # If previously matched, verify it's for the correct key.
-          if [[ $l =~ "^\"?${key[-1]}\"? =" ]]; then
-            s$op ${match[1]//Apple Global Domain/NSGlobalDomain} ${key[-1]}
-          fi
-          unset match
+    echo "Searching active domains for $key…"
+    op=${op/list/listDomain}
+    while read -r l; do
+      if [[ $l =~ "Found [0-9]+ keys in domain '([^']*)'" ]]; then
+        # If there's a match, skip to next item in the loop.
+      elif [[ -n $match[1] ]]; then
+        # If previously matched, verify it's for the correct key.
+        if [[ $l =~ "^\"?$key[-1]\"? =" ]]; then
+          s$op ${match[1]//Apple Global Domain/NSGlobalDomain} $key[-1]
         fi
-      done < <( defaults find ${key[-1]} )
-    fi
+        unset match
+      fi
+    done < <( defaults find $key[-1] )
+
   else
     domain=${domain[-1]/-(globalDomain|g)/NSGlobalDomain}
 
-    # [backup|restore|list] all keys for all backed up domains.
-    if [[ $key == (-e|--existing) ]]; then
-      while read -r d; do
-        echo "Getting existing keys for $d…"
-        while read -r k; do
-          s$op $d $k
-        done < <( sgetIndex $d )
-      done < <( [[ -n $domain ]] && echo $domain || sgetDomains )
-
-    # [backup|restore] a specific key for specific domain.
-    elif [[ -n $domain && -n $key && $op != list ]]; then
-      echo "Getting ${key[-1]} for $domain…"
-      s$op $domain ${key[-1]}
-
-    # [list] all backed up domains that contains a given key.
-    elif [[ $op == list && -n $key ]]; then
+    # list all domains for a given key.
+    if [[ $op == list && -n $key[-1] ]]; then
       echo "Getting domains for $key…"
       while read -r d; do
-        skeyExists $d ${key[-1]} &&
+        skeyExists $d $key[-1] &&
           echo "  $d"
       done < <( sgetDomains )
 
-    elif [[ $op == backup && -n $key ]]; then
-      echo "Missing -s flag for $key or use -e without -s." >&2
-      shelp 1
-    else
-      echo "Cannot $op $key!" >&2
-      shelp 1
-    fi
+    # [backup|restore] a specific key for specific domain.
+    elif [[ -n $domain && -n $key[-1] ]]; then
+      echo "Getting $key[-1] for $domain…"
+      s$op $domain $key[-1]
 
+    else
+    # [backup|restore|list] from saved keys.
+    # - filter by domain - applies to all keys within a domain.
+    # - filter by key    - applies to a key across all domains.
+      while read -r d; do
+        echo "Getting existing keys for $d…"
+        while read -r k; do
+          if [[ -z $domain || $domain == $d ]] &&
+             [[ -z $key[-1] || $key[-1] == $k ]]; then
+            s$op $d $k
+          fi
+        done < <( sgetIndex $d )
+      done < <( [[ -n $domain ]] && echo $domain || sgetDomains )
+
+    fi
   fi
 } $@
