Various changes:
- Removed the ability to restore when the domain doesn't exist already.
  This is due to how the defaults command finds the target. It's not
  always ~/Library/Preferences. Sandboxed apps could end up ignoring the
  setting if the app wasn't installed before the restore was done.
- The above domain check is also done for backups to be more informative
  when redoing a backup to a non-existent domain.
- Enables error exit status.
- More informative function names.

diff --git a/.config/backup/bdefaults b/.config/backup/bdefaults
--- a/.config/backup/bdefaults
+++ b/.config/backup/bdefaults
@@ -31,6 +31,11 @@ function shelp {
 function sbackup {
   local type value index plist=$bdpath/$1.plist
 
+  if ! ssourceDomainExists $1; then
+    echo "? $1 - source domain does not exist!"
+    return 1
+  fi
+
   # Keys from `defaults read-type` translated to values accepted by plutil.
   # Data, date, arrays and dictionaries must be added as xml.
   typeset -A types=(
@@ -65,12 +70,13 @@ function sbackup {
     # Escape dots or plutil will drill into submembers.
     if plutil -replace "${2//\./\\.}" $type $value $plist; then
       echo "  $@[$3] - saved"
-      if ! sgetIndex $1 | grep -qx $2; then
+      if ! sgetSettingsIndex $1 | grep -qx $2; then
         plutil -insert SettingsIndex -string $2 -append $plist
       fi
     fi
   else
-    echo "? $@[$3] - does not exist!" >&2
+    echo "? $@[$3] - source key does not exist!" >&2
+    return 1
   fi
 }
 
@@ -78,12 +84,17 @@ function sbackup {
 # $2 key
 # $3 output 1 = domain or 2 = key
 function srestore {
+  if ! ssourceDomainExists $1; then
+    echo "? $1 - restore target does not exist!"
+    return 1
+  fi
   local value
   if value=`plutil -extract "${2//\./\\.}" xml1 -o - $bdpath/$1.plist 2>/dev/null`; then
     defaults write $1 $2 "$value" &&
       echo "  $@[$3] - restored"
   else
-    echo "!!$@[$3] - failed!" >&2
+    echo "!!$@[$3] - failed reading backup!" >&2
+    return 1
   fi
 }
 
@@ -91,12 +102,13 @@ function srestore {
 # $2 key
 # $3 output 1 = domain or 2 = key
 function sdelete {
-  if l=`sgetIndex $1 | grep -nx $2`; then
+  if l=`sgetSettingsIndex $1 | grep -nx $2`; then
     plutil -remove SettingsIndex.$((${l/:*} - 1)) $bdpath/$1.plist
     plutil -remove "${2//\./\\.}" $bdpath/$1.plist &&
       echo "  $@[$3] - deleted"
   else
-    echo "!!$@[$3] - does not exist!" >&2
+    echo "!!$@[$3] - backup key does not exist!" >&2
+    return 1
   fi
 }
 
@@ -114,21 +126,29 @@ function slistDomain {
 
 # $1 domain
 # $2 key
-function skeyExists {
-  sgetIndex $1 | grep -qx $2
+function sbackupKeyExists {
+  sgetSettingsIndex $1 | grep -qx $2
 }
 
 # $1 domain
-function sgetIndex {
+function ssourceDomainExists {
+  if [[ -z $_dd ]]; then
+    _dd=`defaults domains`; _dd=${_dd//, /\\n}
+  fi
+  [[ $1 == NSGlobalDomain ]] &&
+    return 0 ||
+    echo $_dd | grep -qx $1
+}
+
+# $1 domain
+function sgetSettingsIndex {
   c=`plutil -extract SettingsIndex raw $bdpath/$1.plist`
   if [[ $c > 0 ]]; then
-    for n in {0..$((c-1))}; do
-      plutil -extract SettingsIndex.$n raw $bdpath/$1.plist
-    done
+    for n in {0..$((c-1))}; plutil -extract SettingsIndex.$n raw $bdpath/$1.plist
   fi
 }
 
-function sgetDomains {
+function sgetBackupDomains {
   for d in $bdpath/*.plist(N); echo $d:r:t
 }
 
@@ -191,6 +211,7 @@ function {
   if [[ -n $search ]]; then
 
     echo "Searching active domains for $key:"
+    # [backup|list] from search.
     op=${op/list/listDomain}
     while read -r l; do
       if [[ $l =~ "^Found [0-9]+ keys in domain '([^']*)': {$" ]]; then
@@ -212,17 +233,17 @@ function {
     if [[ $op == list && -n $key ]]; then
       echo "${(C)op} domains for $key:"
       while read -r d; do
-        ! skeyExists $d $key[-1] ||
+        ! sbackupKeyExists $d $key[-1] ||
           echo "  $d"
-      done < <( sgetDomains )
+      done < <( sgetBackupDomains )
 
-    # [backup|restore] a specific key for specific domain.
+    # [backup|restore|delete] a specific key for specific domain.
     elif [[ -n $domain && -n $key ]]; then
       echo "${(C)op} $key[-1] for $domain:"
       s$op $domain $key[-1] 2
 
     else
-    # [backup|restore|list] from saved keys. One filter allowed.
+    # [backup|restore|list|delete] from saved keys. One filter allowed.
     # - filter by domain - applies to all keys within a domain.
     # - filter by key    - applies to a key across all domains.
       while read -r d; do
@@ -235,9 +256,9 @@ function {
             fi
             s$op $d $k 2
           fi
-        done < <( sgetIndex $d )
+        done < <( sgetSettingsIndex $d )
         unset h
-      done < <( [[ -n $domain ]] && echo $domain || sgetDomains )
+      done < <( [[ -n $domain ]] && echo $domain || sgetBackupDomains )
 
     fi
   fi
